//! Spike-vs-production A/B parity test for the four decode lanes.
//!
//! This test verifies the acceptance criterion: "direct M5 spike-harness
//! comparisons produce byte-identical token streams for all four lanes."
//! It loads the same model checkpoints, runs the same 20-prompt x 64-token
//! fixture protocol, and compares the production owned-decode-engine's token
//! streams against the spike harness's reference fixtures byte-for-byte.
//!
//! Checkpoint-gated: set the model path env vars to run. The test is
//! `#[ignore]` by default so it only runs on the macos-metal CI lane or
//! when explicitly invoked.
//!
//! Oracle independence: the LFM2 lanes compare against CPU-reference
//! fixtures generated by the spike's CPU decode implementation (independent
//! of any Metal engine). The Qwen3 lanes compare against the spike Metal
//! step engine's recorded output — a port-fidelity oracle (valid because the
//! `.metal`/`.m`/FFI surface is byte-identical to the spike). The
//! CPU-oracle-backed exactness chain for the spike engine's Qwen3 arithmetic
//! lives in the spike's own gate history: `bench/spikes/unified-rt/
//! DECODE-FOUNDATIONS.md` ("Token-exact gate", `reference_qwen3_decode.py`,
//! transformers 4.51.0 + torch 2.13.0 CPU fp32 oracle, 20/20 prompts and
//! 1280/1280 tokens exact, zero near-tie exemptions). The streams pinned
//! here were recorded by that same spike engine on the Qwen3-Embedding-0.6B
//! variant; they are pinned in `bench/spikes/unified-rt/fixtures/` with
//! their sha256 recorded below, so neither engine can silently drift the
//! reference, and they are never regenerated from the production engine.
//!
//! Env vars:
//! - `SYNAPSE_OWNED_DECODE_QWEN3_0_6B`: path to the Qwen3-Embedding-0.6B snapshot
//! - `SYNAPSE_OWNED_DECODE_LFM2_1_2B`: path to the LFM2-1.2B snapshot
//! - `SYNAPSE_OWNED_DECODE_SPIKE_REFERENCES`: path to the spike's reference
//!   fixture directory (bench/spikes/unified-rt/fixtures)
//! - `SYNAPSE_OWNED_DECODE_SPIKE_QWEN3_REFERENCES`: optional override for the
//!   directory holding the pinned Qwen3 spike fixtures. The pinned sha256
//!   still has to match, so this relocates the fixtures; it cannot substitute
//!   a different reference.
//!
//! Run with:
//! ```text
//! DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
//! SYNAPSE_OWNED_DECODE_QWEN3_0_6B=<qwen3-snapshot> \
//! SYNAPSE_OWNED_DECODE_LFM2_1_2B=<lfm2-snapshot> \
//! SYNAPSE_OWNED_DECODE_SPIKE_REFERENCES=<spike-fixtures-dir> \
//! cargo test -p synapse-engine-owned --release --test owned_decode_parity -- --ignored --nocapture
//! ```

#![cfg(target_os = "macos")]

use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use serde::Deserialize;
use sha2::{Digest, Sha256};
use tokenizers::Tokenizer;

#[allow(unused_imports, clippy::too_many_arguments, dead_code)]
use synapse_engine_owned::owned_decode_engine::{
    top_logits, DecodeKernel, Lfm2DecodeModel, Lfm2HybridStepEngine, MetalStepDecoder,
    MetalStepKvCache, Qwen3DecodeModel, WeightQuantization,
};
use synapse_engine_owned::Precision;

/// One row from the spike's decode-prompts.jsonl fixture.
#[derive(Clone, Deserialize)]
struct DecodePrompt {
    id: String,
    prompt: String,
}

/// One row from the spike's reference fixture JSONL (lfm2-f16-step-reference.jsonl etc).
#[derive(Clone, Deserialize)]
struct ReferenceRow {
    id: String,
    tokens: Vec<u32>,
}

/// One row from the spike's CLI output JSON (Qwen3 lanes).
#[derive(Clone, Deserialize)]
struct SpikeCliOutput {
    results: Vec<SpikeCliResult>,
}

#[derive(Clone, Deserialize)]
struct SpikeCliResult {
    id: String,
    tokens: Vec<u32>,
}

/// Load the 20-prompt decode fixture (decode-prompts.jsonl).
fn load_decode_prompts() -> Vec<DecodePrompt> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../bench/spikes/unified-rt/decode-prompts.jsonl");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read decode-prompts.jsonl at {}: {error}", path.display()));
    raw.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).expect("decode-prompts.jsonl row parses"))
        .collect()
}

/// Load a spike reference fixture (lfm2-f16-step-reference.jsonl etc).
fn load_reference_fixture(name: &str) -> HashMap<String, Vec<u32>> {
    let spike_fixtures = std::env::var_os("SYNAPSE_OWNED_DECODE_SPIKE_REFERENCES")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../bench/spikes/unified-rt/fixtures")
        });
    let path = spike_fixtures.join(name);
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {name} at {}: {error}", path.display()));
    raw.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| {
            let row: ReferenceRow =
                serde_json::from_str(line).expect("reference fixture row parses");
            (row.id, row.tokens)
        })
        .collect()
}

/// Load a pinned Qwen3 spike reference fixture and verify its sha256.
///
/// These fixtures are the spike Metal step engine's recorded 20x64 greedy
/// token streams (spike CLI, `--decode-backend metal-step`), pinned in
/// `bench/spikes/unified-rt/fixtures/`. The sha256 of the exact pinned bytes
/// is recorded in the call site: any modification or regeneration of the
/// reference — by either engine — fails the gate until the hash is
/// deliberately re-pinned. The CPU-oracle-backed exactness chain behind the
/// streams lives in the spike's gate history (DECODE-FOUNDATIONS.md,
/// "Token-exact gate"); this test never regenerates the reference from the
/// production engine.
fn load_spike_qwen3_output(name: &str, pinned_sha256: &str) -> HashMap<String, Vec<u32>> {
    let spike_dir = std::env::var_os("SYNAPSE_OWNED_DECODE_SPIKE_QWEN3_REFERENCES")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../bench/spikes/unified-rt/fixtures")
        });
    let path = spike_dir.join(name);
    let raw = std::fs::read(&path)
        .unwrap_or_else(|error| panic!("read {name} at {}: {error}", path.display()));
    let digest = Sha256::digest(&raw);
    let hex = digest
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    assert_eq!(
        hex, pinned_sha256,
        "pinned Qwen3 spike reference {name} drifted: sha256 {hex} != pinned {pinned_sha256}. \
         The reference is immutable; re-pinning requires a deliberate hash update in this test."
    );
    let output: SpikeCliOutput =
        serde_json::from_slice(&raw).expect("pinned spike reference parses");
    output
        .results
        .into_iter()
        .map(|r| (r.id, r.tokens))
        .collect()
}

/// Greedy-decode one prompt through the Qwen3 Metal step engine.
/// For Q8, the spike uses f16 weights for prefill (via the MPSGraph decoder)
/// and Q8 weights for stepping. The production port replicates this by
/// running prefill with an f16 engine, exporting the KV cache bits, importing
/// them into the Q8 engine, then stepping with Q8. This matches the spike
/// byte-for-byte.
#[allow(clippy::too_many_arguments)]
fn qwen3_greedy_decode(
    f16_decoder: &mut Option<MetalStepDecoder>,
    q8_decoder: &mut MetalStepDecoder,
    model: &Qwen3DecodeModel,
    tokenizer: &Tokenizer,
    prompt: &str,
    max_tokens: usize,
    stop_tokens: &HashSet<u32>,
    weight_quant: WeightQuantization,
) -> Vec<u32> {
    let encoding = tokenizer.encode(prompt, true).expect("encode Qwen3 prompt");
    let prompt_ids = encoding.get_ids().to_vec();
    assert!(!prompt_ids.is_empty(), "Qwen3 prompt produced no tokens");

    let (first, mut cache) = if weight_quant.is_quantized() {
        // Q8: prefill with f16 engine, export KV cache, import into Q8 engine.
        let f16 = f16_decoder.as_mut().expect("f16 decoder for Q8 prefill");
        let (f16_cache, first) = f16.prefill(&prompt_ids).expect("f16 prefill");
        // Export KV cache bits from the f16 engine.
        let one_layer_elements = 2 * model.config.num_key_value_heads * 512 * model.config.head_dim;
        let mut cache_bits = Vec::with_capacity(model.layers.len() * one_layer_elements);
        for layer in 0..model.layers.len() {
            cache_bits.extend(f16.inspect_cache_bits(layer).expect("export f16 cache"));
        }
        // Import into the Q8 engine.
        q8_decoder
            .import_caches(&cache_bits)
            .expect("import caches into Q8");
        let q8_cache = MetalStepKvCache {
            position: f16_cache.position,
        };
        (first, q8_cache)
    } else {
        // f16: prefill and step with the same engine.
        let (cache, first) = q8_decoder.prefill(&prompt_ids).expect("f16 prefill");
        (first, cache)
    };

    let mut generated = Vec::with_capacity(max_tokens);
    generated.push(first);
    if stop_tokens.contains(&first) || max_tokens <= 1 {
        return generated;
    }

    // Chain the remaining tokens.
    let remaining = max_tokens - 1;
    let chain_steps = remaining.min(q8_decoder.capacity() - cache.position);
    if chain_steps > 0 {
        let tokens = q8_decoder
            .advance_chain(&mut cache, first, chain_steps)
            .expect("metal chain");
        for token in tokens {
            generated.push(token);
            if stop_tokens.contains(&token) {
                break;
            }
        }
    }
    generated
}

/// Greedy-decode one prompt through the LFM2 hybrid step engine.
fn lfm2_greedy_decode(
    engine: &mut Lfm2HybridStepEngine,
    _model: &Lfm2DecodeModel,
    tokenizer: &Tokenizer,
    prompt: &str,
    max_tokens: usize,
    stop_tokens: &HashSet<u32>,
) -> Vec<u32> {
    engine.reset().expect("reset caches");
    let encoding = tokenizer.encode(prompt, true).expect("encode LFM2 prompt");
    let prompt_ids = encoding.get_ids().to_vec();
    assert!(!prompt_ids.is_empty(), "LFM2 prompt produced no tokens");

    // Prefill via the hybrid step engine's verify path.
    let first = engine.prefill(&prompt_ids).expect("metal prefill");
    let mut generated = Vec::with_capacity(max_tokens);
    generated.push(first);
    if stop_tokens.contains(&first) || max_tokens <= 1 {
        return generated;
    }
    // Chain the remaining tokens.
    let position = prompt_ids.len();
    let remaining = max_tokens - 1;
    let chain_steps = remaining.min(engine.capacity() - position);
    if chain_steps > 0 {
        let tokens = engine
            .chain(position, chain_steps, first)
            .expect("metal chain");
        for token in tokens {
            generated.push(token);
            if stop_tokens.contains(&token) {
                break;
            }
        }
    }
    generated
}

/// Compare production token streams against spike references and report.
struct ParityReport {
    lane: &'static str,
    total: usize,
    byte_identical: usize,
    forks: Vec<(String, usize, u32, u32)>, // (id, step, prod_token, spike_token)
}

impl ParityReport {
    fn assert_byte_identical(&self) {
        if self.forks.is_empty() {
            println!(
                "[parity] {} {}/{} prompts byte-identical vs spike",
                self.lane, self.byte_identical, self.total
            );
            return;
        }
        for (id, step, prod, spike) in &self.forks {
            println!(
                "[parity] {} DIVERGENCE {}: step {} prod {} vs spike {}",
                self.lane, id, step, prod, spike
            );
        }
        panic!(
            "[parity] {} {}/{} byte-identical; {} fork(s) — spike-vs-production parity failed",
            self.lane,
            self.byte_identical,
            self.total,
            self.forks.len()
        );
    }
}

/// Compare two token streams, returning the first divergence if any.
fn compare_tokens(prod: &[u32], spike: &[u32]) -> Option<(usize, u32, u32)> {
    let min_len = prod.len().min(spike.len());
    for step in 0..min_len {
        if prod[step] != spike[step] {
            return Some((step, prod[step], spike[step]));
        }
    }
    if prod.len() != spike.len() {
        // Length mismatch counts as a divergence at the shorter stream's end.
        return Some((min_len, 0, 0));
    }
    None
}

fn run_qwen3_lane(
    lane: &'static str,
    weight_quant: WeightQuantization,
    spike_reference: &HashMap<String, Vec<u32>>,
) -> ParityReport {
    let qwen3_path = PathBuf::from(
        std::env::var_os("SYNAPSE_OWNED_DECODE_QWEN3_0_6B")
            .expect("set SYNAPSE_OWNED_DECODE_QWEN3_0_6B to the Qwen3-Embedding-0.6B snapshot"),
    );
    let mut tokenizer =
        Tokenizer::from_file(qwen3_path.join("tokenizer.json")).expect("load Qwen3 tokenizer");
    tokenizer.with_padding(None);
    tokenizer
        .with_truncation(None)
        .expect("disable Qwen3 truncation");

    // For Q8, the spike uses f16 weights for prefill (via MPSGraph) and Q8 for
    // stepping. We replicate this by loading an f16 model for prefill and a Q8
    // model for stepping. For f16, a single model/engine suffices.
    let f16_model = if weight_quant.is_quantized() {
        Some(
            Qwen3DecodeModel::load_with_quant(
                &qwen3_path.join("model.safetensors"),
                Precision::F16,
                WeightQuantization::None,
            )
            .expect("load Qwen3 f16 model for Q8 prefill"),
        )
    } else {
        None
    };
    let f16_decoder = f16_model.as_ref().map(|model| {
        MetalStepDecoder::new(model, Precision::F16, 512, WeightQuantization::None)
            .expect("create Qwen3 f16 decoder for Q8 prefill")
    });

    let model = Qwen3DecodeModel::load_with_quant(
        &qwen3_path.join("model.safetensors"),
        Precision::F16,
        weight_quant,
    )
    .expect("load Qwen3 decode model");
    let mut decoder = MetalStepDecoder::new(&model, Precision::F16, 512, weight_quant)
        .expect("create Qwen3 Metal step decoder");

    let stop_tokens = model.generation_stop_ids().iter().copied().collect();
    let prompts = load_decode_prompts();
    let mut byte_identical = 0;
    let mut forks = Vec::new();
    let mut f16_dec = f16_decoder;

    for prompt in &prompts {
        let prod_tokens = qwen3_greedy_decode(
            &mut f16_dec,
            &mut decoder,
            &model,
            &tokenizer,
            &prompt.prompt,
            64,
            &stop_tokens,
            weight_quant,
        );
        let spike_tokens = spike_reference
            .get(&prompt.id)
            .unwrap_or_else(|| panic!("spike reference missing prompt {}", prompt.id));
        match compare_tokens(&prod_tokens, spike_tokens) {
            None => byte_identical += 1,
            Some((step, prod, spike)) => {
                forks.push((prompt.id.clone(), step, prod, spike));
            }
        }
    }

    ParityReport {
        lane,
        total: prompts.len(),
        byte_identical,
        forks,
    }
}

/// Qwen3 f16 lane: production engine vs the pinned spike Metal step engine
/// stream (port-fidelity oracle; the CPU-oracle exactness chain behind the
/// pinned stream is documented in the module docs).
#[test]
#[ignore]
fn parity_qwen3_f16() {
    let spike_ref = load_spike_qwen3_output(
        "spike-qwen3-f16.jsonl",
        "c3080813c45c364a73cbb6dce122afbba20e761b2189a31d0055ecf435232af1",
    );
    let report = run_qwen3_lane("qwen3-f16", WeightQuantization::None, &spike_ref);
    report.assert_byte_identical();
}

/// Qwen3 Q8_0 lane: production engine vs the pinned spike Metal step engine
/// stream (f16 prefill + Q8 stepping, as the spike runs it).
#[test]
#[ignore]
fn parity_qwen3_q8() {
    let spike_ref = load_spike_qwen3_output(
        "spike-qwen3-q8.jsonl",
        "e9165dbbe4746a2fad30fd94bad344601408a689e308fad748dc7132606f83d8",
    );
    let report = run_qwen3_lane("qwen3-q8", WeightQuantization::Q8_0, &spike_ref);
    report.assert_byte_identical();
}

/// Certified near-tie fork signatures for the LFM2 f16 lane:
/// (prompt id, step, production token, CPU-oracle token). The M5 build host
/// forks at completion-15/step 17: the engine emits 523 where the CPU oracle
/// emits 518 — the CPU top-2 pair is exactly (518, 523) with gap 0.000362,
/// inside the 0.05 structural band, so the fork is a certified top-2 swap.
/// The spike's Metal step engine produces the same fork on this machine and
/// the production engine is byte-identical to it. Recertifying on another
/// machine requires recording that machine's exact signature here.
const LFM2_F16_CERTIFIED_FORKS: &[(&str, usize, u32, u32)] = &[("completion-15", 17, 523, 518)];

/// Structural-band ceiling for the LFM2 f16 lane: at most two top-2 swaps
/// (structural-band-v1 manifest, lfm2-1.2b/f16).
const LFM2_F16_MAX_CERTIFIED_FORKS: usize = 2;

/// LFM2 f16 lane: compare the production engine against the CPU reference
/// fixture (the oracle).
///
/// GPU f16 execution may legitimately pick the second-best token when the top
/// two logits are nearly tied. The gate accepts at most
/// `LFM2_F16_MAX_CERTIFIED_FORKS` divergences AND requires every accepted
/// fork to match a pinned signature in `LFM2_F16_CERTIFIED_FORKS` exactly —
/// prompt id, step index, and both tokens of the recorded top-2 swap. A fork
/// at any other prompt or step, or with any other token pair, fails the gate
/// even when the total fork count is within the ceiling.
#[test]
#[ignore]
fn parity_lfm2_f16() {
    let lfm2_path = PathBuf::from(
        std::env::var_os("SYNAPSE_OWNED_DECODE_LFM2_1_2B")
            .expect("set SYNAPSE_OWNED_DECODE_LFM2_1_2B to the LFM2-1.2B snapshot"),
    );
    let mut tokenizer =
        Tokenizer::from_file(lfm2_path.join("tokenizer.json")).expect("load LFM2 tokenizer");
    tokenizer.with_padding(None);
    tokenizer
        .with_truncation(None)
        .expect("disable LFM2 truncation");

    let model = Lfm2DecodeModel::load(&lfm2_path.join("model.safetensors"), Precision::F16)
        .expect("load LFM2 decode model");
    let mut engine =
        Lfm2HybridStepEngine::new(&model, Precision::F16, 512, WeightQuantization::None)
            .expect("create LFM2 hybrid step engine");

    let stop_tokens = model.generation_stop_ids().iter().copied().collect();
    let prompts = load_decode_prompts();
    let spike_ref = load_reference_fixture("lfm2-f16-step-reference.jsonl");
    let mut byte_identical = 0;
    let mut forks = Vec::new();

    for prompt in &prompts {
        let prod_tokens = lfm2_greedy_decode(
            &mut engine,
            &model,
            &tokenizer,
            &prompt.prompt,
            64,
            &stop_tokens,
        );
        let spike_tokens = spike_ref
            .get(&prompt.id)
            .unwrap_or_else(|| panic!("spike reference missing prompt {}", prompt.id));
        match compare_tokens(&prod_tokens, spike_tokens) {
            None => byte_identical += 1,
            Some((step, prod, spike)) => {
                forks.push((prompt.id.clone(), step, prod, spike));
            }
        }
    }

    let report = ParityReport {
        lane: "lfm2-f16",
        total: prompts.len(),
        byte_identical,
        forks,
    };
    // The spike's Metal engine is known to diverge from the CPU oracle on
    // prompt completion-15 at step 17, where the top-two logit gap is only
    // 0.000362 — a hardware rounding coin-flip, not an arithmetic bug. The
    // production engine must reproduce the spike's behavior, so accept forks
    // that match the pinned certified signature exactly (prompt id, step, and
    // both tokens of the recorded top-2 swap), up to the structural-band
    // ceiling; any other fork is a parity failure.
    let uncertified = report
        .forks
        .iter()
        .filter(|(id, step, prod, oracle)| {
            !LFM2_F16_CERTIFIED_FORKS.contains(&(id.as_str(), *step, *prod, *oracle))
        })
        .collect::<Vec<_>>();
    if report.forks.len() <= LFM2_F16_MAX_CERTIFIED_FORKS && uncertified.is_empty() {
        println!(
            "[parity] lfm2-f16 {}/{} byte-identical vs CPU oracle; {} certified fork(s) matching the pinned signature — matches spike Metal step engine",
            report.byte_identical,
            report.total,
            report.forks.len()
        );
        for (id, step, prod, oracle) in &report.forks {
            println!(
                "[parity] lfm2-f16 certified fork {}: step {} prod {} vs oracle {} — pinned top-2 swap signature",
                id, step, prod, oracle
            );
        }
    } else {
        for (id, step, prod, oracle) in &uncertified {
            println!(
                "[parity] lfm2-f16 UNCERTIFIED fork {}: step {} prod {} vs oracle {} — no pinned signature matches",
                id, step, prod, oracle
            );
        }
        report.assert_byte_identical();
    }

    // Single-token advance cross-check: the host-gathered embedding path must
    // select the same next token as one device-gathered chained step from the
    // same cache state. Two fresh engines keep the comparison state-clean
    // (the rolling conv caches advance in place and cannot be rewound).
    // `DecodeKernel::prefill` is called through the trait explicitly because
    // the engine's inherent `prefill` (returning only the argmax) shadows it.
    let probe_prompt = prompts[0].prompt.as_str();
    let probe_ids = tokenizer
        .encode(probe_prompt, true)
        .expect("encode LFM2 probe prompt")
        .get_ids()
        .to_vec();
    let mut advance_engine =
        Lfm2HybridStepEngine::new(&model, Precision::F16, 512, WeightQuantization::None)
            .expect("create advance probe engine");
    let mut chain_engine =
        Lfm2HybridStepEngine::new(&model, Precision::F16, 512, WeightQuantization::None)
            .expect("create chain probe engine");
    let (mut advance_cache, first_a) =
        DecodeKernel::prefill(&mut advance_engine, &probe_ids).expect("advance probe prefill");
    let (mut chain_cache, first_b) =
        DecodeKernel::prefill(&mut chain_engine, &probe_ids).expect("chain probe prefill");
    assert_eq!(first_a, first_b, "prefill argmax is deterministic");
    let advance_logits = advance_engine
        .advance(&mut advance_cache, first_a)
        .expect("advance with host-gathered embedding");
    let advance_token = top_logits(&advance_logits, 1)[0].token_id;
    let chain_tokens = chain_engine
        .advance_chain(&mut chain_cache, first_b, 1)
        .expect("one chained step");
    assert_eq!(
        advance_token, chain_tokens[0],
        "single-token advance (host gather) must match one chained step (device gather)"
    );
    assert_eq!(
        advance_engine.cache_position(&advance_cache),
        chain_engine.cache_position(&chain_cache),
        "both probe caches advanced one position"
    );
    println!("[parity] lfm2-f16 advance/chain cross-check: token {advance_token} matches");
}

/// LFM2 Q8_0 lane: production engine vs spike reference fixture.
#[test]
#[ignore]
fn parity_lfm2_q8() {
    let lfm2_path = PathBuf::from(
        std::env::var_os("SYNAPSE_OWNED_DECODE_LFM2_1_2B")
            .expect("set SYNAPSE_OWNED_DECODE_LFM2_1_2B to the LFM2-1.2B snapshot"),
    );
    let mut tokenizer =
        Tokenizer::from_file(lfm2_path.join("tokenizer.json")).expect("load LFM2 tokenizer");
    tokenizer.with_padding(None);
    tokenizer
        .with_truncation(None)
        .expect("disable LFM2 truncation");

    let model = Lfm2DecodeModel::load_with_quant(
        &lfm2_path.join("model.safetensors"),
        Precision::F16,
        WeightQuantization::Q8_0,
    )
    .expect("load LFM2 Q8 decode model");
    let mut engine =
        Lfm2HybridStepEngine::new(&model, Precision::F16, 512, WeightQuantization::Q8_0)
            .expect("create LFM2 Q8 hybrid step engine");

    let stop_tokens = model.generation_stop_ids().iter().copied().collect();
    let prompts = load_decode_prompts();
    let spike_ref = load_reference_fixture("lfm2-q8-step-reference.jsonl");
    let mut byte_identical = 0;
    let mut forks = Vec::new();

    for prompt in &prompts {
        let prod_tokens = lfm2_greedy_decode(
            &mut engine,
            &model,
            &tokenizer,
            &prompt.prompt,
            64,
            &stop_tokens,
        );
        let spike_tokens = spike_ref
            .get(&prompt.id)
            .unwrap_or_else(|| panic!("spike reference missing prompt {}", prompt.id));
        match compare_tokens(&prod_tokens, spike_tokens) {
            None => byte_identical += 1,
            Some((step, prod, spike)) => {
                forks.push((prompt.id.clone(), step, prod, spike));
            }
        }
    }

    let report = ParityReport {
        lane: "lfm2-q8",
        total: prompts.len(),
        byte_identical,
        forks,
    };
    report.assert_byte_identical();
}
