#!/usr/bin/env python3
"""Render only the aggregate measurement; never open private evaluation inputs."""
import argparse
import json
from pathlib import Path

NAMES = {"fp32": "fp32", "f16": "f16", "q8_0": "Q8_0 simulated",
         "channel": "per-channel W8", "w8a8": "W8A8", "gguf": "consumer GGUF Q8_0"}


def render(report):
    lines = ["# Aggregate quality tables", "", "Generated by `render_tables.py` from `aggregate.json`.", "",
             "Cosines compare each tool's unique query/document vectors with fp32. Ranking",
             "overlap includes complete empty pools as zero; Kendall τ excludes pools",
             "with fewer than two candidates. Sol uses ordered relevant top-10 prefixes,",
             "not the entire relevant membership set. See the README for the denominator.", ""]
    for model, info in report["models"].items():
        for tool, group in info["quality"].items():
            stats = group["schemes"]
            lines += [f"## {model} / {tool}", "",
                      f"{group['queries']} queries; {group['cosine_unique_vectors']} unique vectors; "
                      f"τ defined for {stats['f16']['vs_fp32']['tau_queries']} pools.", "",
                      "| Scheme | Cosine min / p1 / p50 | vs fp32 overlap / τ | vs f16 overlap / τ | Sol overlap A / B / mean | Δsol vs f16 [paired 95% CI] |",
                      "|---|---|---|---|---|---|"]
            for scheme, s in stats.items():
                c, r, f, j, d = (s[k] for k in ("cosine_fp32", "vs_fp32", "vs_f16", "sol_overlap10", "sol_delta_f16"))
                lines.append(f"| {NAMES[scheme]} | {c['min']:.6f} / {c['p1']:.6f} / {c['p50']:.6f} | "
                             f"{r['overlap10']:.6f} / {r['tau']:.6f} | {f['overlap10']:.6f} / {f['tau']:.6f} | "
                             f"{j['A']:.6f} / {j['B']:.6f} / {j['mean']:.6f} | "
                             f"{d['mean']:+.6f} [{d['ci95'][0]:+.6f}, {d['ci95'][1]:+.6f}] |")
            lines += ["", f"F16 mean absolute per-query Sol A/B movement: **{group['f16_judge_mean_abs_A_B']:.6f}**. "
                      f"Sol B/A repeat overlap: **{group['sol_B_vs_A_overlap']:.6f}** "
                      f"(n={group['sol_repeat_queries']}).", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", type=Path, required=True)
    p.add_argument("--output", type=Path, required=True)
    args = p.parse_args()
    report = json.loads(args.input.read_text())
    args.output.write_text(render(report))
    print("rendered", len(report["models"]), "models and",
          sum(len(g["schemes"]) for m in report["models"].values() for g in m["quality"].values()), "table rows")
