//! The ModernBERT residual-stream rotation, generated in code.
//!
//! The matrix is deterministic, so it is rebuilt on demand rather than stored;
//! `models.json` pins the SHA-256 of its bytes and every consumer (the
//! validator and the converter) regenerates it and refuses on a mismatch.
//!
//! Construction (rotation id `modernbert-hadamard-768-v2`):
//!
//! - `H12` is the 12 × 12 Paley type I Hadamard matrix for q = 11. With `χ`
//!   the quadratic character mod 11 (`χ(0) = 0`, `+1` on nonzero squares,
//!   `−1` otherwise) and the Jacobsthal matrix `J[i][j] = χ(j − i)`, the
//!   skew matrix is `S = [[0, 1ᵀ], [−1, J]]` and `H12 = I + S`.
//! - `H64` is the 64 × 64 Sylvester Hadamard matrix,
//!   `H64[i][j] = (−1)^popcount(i & j)`.
//! - `K = H12 ⊗ H64`, so `K[64a + b][64c + d] = H12[a][c] · H64[b][d]`.
//! - Row `r` of `K` is multiplied by a sign `s_r` (row sign flips, `D K`),
//!   and every entry is scaled by `1/√768`: `Q = D K / √768`. Since
//!   `K Kᵀ = 768 I` and `D² = I`, `Q Qᵀ = I`.
//! - Signs come from a counter-based generator built on SHA-256 alone, so no
//!   library RNG whose stream could change between versions is involved.
//!   Row `r` uses block `k = r / 256` and bit `i = r % 256` of
//!   `SHA-256(b"modernbert-hadamard-768" ‖ seed as u64 LE ‖ k as u64 LE)`,
//!   where bit `i` is `(digest[i / 8] >> (i % 8)) & 1` (least significant bit
//!   first within a byte). A set bit means `s_r = −1`.
//!
//! The bytes are the matrix in row-major order, each entry a little-endian
//! f64. Every entry is exactly `±(1.0 / √768)` with both operations correctly
//! rounded IEEE f64, so the bytes do not depend on platform or compiler.
//!
//! This is not the numpy-generated matrix used in the measurements under
//! docs/evidence/ane-modernbert-rotation-conditioning/, hence the `-v2` id.
//! Any orthonormal rotation preserves the model's output in exact
//! arithmetic, so only the f16 rounding behaviour can differ; the direct-ANE
//! profiles' parity is measured on the converted package, not inherited from
//! that evidence.

use sha2::{Digest, Sha256};

use crate::canonical::sha256_hex;
use crate::manifest::Rotation;
use crate::{perr, Result};

/// Side length of the rotation (ModernBERT-base hidden width).
pub const DIMENSION: usize = 768;
/// Domain-separation prefix hashed ahead of the seed and block counter.
pub const SIGN_DOMAIN: &[u8] = b"modernbert-hadamard-768";
/// The `construction` text `models.json` must carry for this rotation, so the
/// manifest's description cannot drift from the code that builds the matrix.
pub const CONSTRUCTION: &str = "Q = D kron(H12, H64) / sqrt(768): H12 Paley type I (q = 11, H = I + S), H64 Sylvester, D diagonal row signs; row r takes bit r % 256 (LSB first within each byte) of SHA-256(b\"modernbert-hadamard-768\" || sign_seed as u64 LE || r / 256 as u64 LE), set bit = -1; generated by bench/parity/src/hadamard.rs";

/// The 12 × 12 Paley type I Hadamard matrix (q = 11).
pub fn paley12() -> [[i8; 12]; 12] {
    const Q: i64 = 11;
    let chi = |x: i64| -> i8 {
        let x = x.rem_euclid(Q);
        if x == 0 {
            0
        } else if (1..Q).any(|y| (y * y) % Q == x) {
            1
        } else {
            -1
        }
    };
    let mut h = [[0i8; 12]; 12];
    for (i, row) in h.iter_mut().enumerate() {
        for (j, cell) in row.iter_mut().enumerate() {
            let skew = match (i, j) {
                (0, 0) => 0,
                (0, _) => 1,
                (_, 0) => -1,
                _ => chi(j as i64 - i as i64),
            };
            *cell = skew + i8::from(i == j);
        }
    }
    h
}

/// Entry `(i, j)` of the 64 × 64 Sylvester Hadamard matrix.
pub fn sylvester64(i: usize, j: usize) -> i8 {
    if (i & j).count_ones() % 2 == 0 {
        1
    } else {
        -1
    }
}

/// The row signs `s_r` (`+1` or `−1`) for `seed`, from the SHA-256 counter
/// generator described in the module documentation.
pub fn row_signs(seed: u64) -> Vec<i8> {
    (0..DIMENSION)
        .map(|r| {
            let mut hasher = Sha256::new();
            hasher.update(SIGN_DOMAIN);
            hasher.update(seed.to_le_bytes());
            hasher.update(((r / 256) as u64).to_le_bytes());
            let digest = hasher.finalize();
            let i = r % 256;
            if (digest[i / 8] >> (i % 8)) & 1 == 1 {
                -1
            } else {
                1
            }
        })
        .collect()
}

/// The rotation `Q` for `seed`, row-major.
pub fn generate(seed: u64) -> Vec<f64> {
    let h12 = paley12();
    let signs = row_signs(seed);
    let scale = 1.0 / (DIMENSION as f64).sqrt();
    let mut q = Vec::with_capacity(DIMENSION * DIMENSION);
    for (r, sign) in signs.iter().enumerate() {
        for c in 0..DIMENSION {
            let entry = sign * h12[r / 64][c / 64] * sylvester64(r % 64, c % 64);
            q.push(f64::from(entry) * scale);
        }
    }
    q
}

/// The matrix as row-major little-endian f64 bytes.
pub fn to_bytes(q: &[f64]) -> Vec<u8> {
    q.iter().flat_map(|v| v.to_le_bytes()).collect()
}

/// SHA-256 (hex) of the generated matrix bytes for `seed`.
pub fn digest(seed: u64) -> String {
    sha256_hex(&to_bytes(&generate(seed)))
}

/// Regenerate the matrix a manifest rotation entry describes and refuse it
/// unless its bytes hash to the entry's pinned `sha256`.
pub fn regenerate_checked(name: &str, rotation: &Rotation) -> Result<Vec<f64>> {
    if rotation.dimension as usize != DIMENSION
        || rotation.element != "f64le"
        || rotation.layout != "row_major"
        || rotation.construction != CONSTRUCTION
    {
        return Err(perr!(
            "rotation `{name}` does not describe the generated {DIMENSION}x{DIMENSION} row-major f64le matrix: {rotation:?}"
        ));
    }
    let q = generate(rotation.sign_seed);
    let digest = sha256_hex(&to_bytes(&q));
    if digest != rotation.sha256 {
        return Err(perr!(
            "rotation `{name}` regenerates to SHA-256 {digest}, manifest pins {}",
            rotation.sha256
        ));
    }
    Ok(q)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn paley12_is_hadamard() {
        let h = paley12();
        for i in 0..12 {
            for j in 0..12 {
                let dot: i32 = (0..12)
                    .map(|k| i32::from(h[i][k]) * i32::from(h[j][k]))
                    .sum();
                assert_eq!(dot, if i == j { 12 } else { 0 }, "rows {i},{j}");
                assert!(h[i][j] == 1 || h[i][j] == -1);
            }
        }
    }

    #[test]
    fn rotation_is_orthonormal() {
        let q = generate(0);
        let d = DIMENSION;
        let mut worst = 0f64;
        for i in 0..d {
            for j in 0..d {
                let dot: f64 = (0..d).map(|k| q[i * d + k] * q[j * d + k]).sum();
                let expected = if i == j { 1.0 } else { 0.0 };
                worst = worst.max((dot - expected).abs());
            }
        }
        assert!(worst <= 1e-12, "max |Q Qᵀ − I| = {worst}");
    }

    #[test]
    fn digest_is_stable_across_generations() {
        assert_eq!(digest(0), digest(0));
        assert_eq!(to_bytes(&generate(0)).len(), DIMENSION * DIMENSION * 8);
    }

    #[test]
    fn flipping_one_seed_bit_changes_the_digest() {
        let base = digest(0);
        for bit in [0, 1, 31, 63] {
            assert_ne!(digest(1u64 << bit), base, "seed bit {bit}");
        }
    }

    #[test]
    fn a_rotation_entry_with_another_digest_or_description_is_refused() {
        let good = Rotation {
            sha256: digest(0),
            dimension: DIMENSION as u32,
            element: "f64le".into(),
            layout: "row_major".into(),
            sign_seed: 0,
            construction: CONSTRUCTION.into(),
            scope: "modernbert-residual-stream-v1".into(),
        };
        assert_eq!(regenerate_checked("r", &good).unwrap(), generate(0));
        let mut wrong_digest = good.clone();
        wrong_digest.sha256 = digest(1);
        let error = regenerate_checked("r", &wrong_digest).unwrap_err();
        assert!(error.0.contains("regenerates to SHA-256"), "{error}");
        let mut wrong_seed = good.clone();
        wrong_seed.sign_seed = 1;
        assert!(regenerate_checked("r", &wrong_seed).is_err());
        let mut wrong_text = good;
        wrong_text.construction.push('.');
        assert!(regenerate_checked("r", &wrong_text).is_err());
    }

    #[test]
    fn signs_are_mixed_and_match_the_documented_bit_order() {
        let signs = row_signs(0);
        let negatives = signs.iter().filter(|s| **s == -1).count();
        assert!(
            (300..=468).contains(&negatives),
            "{negatives} negative rows"
        );
        let mut hasher = Sha256::new();
        hasher.update(SIGN_DOMAIN);
        hasher.update(0u64.to_le_bytes());
        hasher.update(1u64.to_le_bytes());
        let block1 = hasher.finalize();
        // Row 256 + 10 reads block 1, byte 1, bit 2.
        let expected = if (block1[1] >> 2) & 1 == 1 { -1 } else { 1 };
        assert_eq!(signs[266], expected);
    }
}
